[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno>=1.7.1",
    "fastapi>=0.115.14",
    "anthropic>=0.40.0",
    "uvicorn>=0.32.1",
    "python-dotenv>=1.0.0",
]
